export const PRODUCTS = [
  {
    name: 'Moringa Munaga Hot & Spicy Powder',
    price: 299,
    originalPrice: 399,
    image: 'https://heweagro.com/wp-content/uploads/2014/08/Hot-Spicy-Powder-img.jpg?resize=500%2C500&ssl=1',
    tag: 'Spicy',
    bestseller: true,
    desc: 'A bold, spicy Moringa blend perfect for rice, roti and dals.',
    ingredients: [
      'Moringa leaf powder',
      'Red chilli',
      'Garlic',
      'Salt',
      'Spices',
    ],
    benefits: [
      'Boosts immunity',
      'Rich in antioxidants',
      'Aids digestion',
      'Anti-inflammatory',
    ],
    nutrition: [
      { label: 'Energy', value: '205 kcal' },
      { label: 'Protein', value: '27.1g' },
      { label: 'Carbohydrates', value: '38.2g' },
      { label: 'Fat', value: '2.3g' },
      { label: 'Fibre', value: '19.2g' },
      { label: 'Calcium', value: '2003mg' },
      { label: 'Iron', value: '28.2mg' },
      { label: 'Vitamin C', value: '17.3mg' },
      { label: 'Vitamin A', value: '18.9mg' },
      { label: 'Potassium', value: '337mg' },
    ],
    howToUse: [
      { icon: 'restaurant-outline', title: 'With Rice', desc: 'Mix with hot rice + ghee' },
      { icon: 'flame-outline', title: 'Curries', desc: 'Add to curries, dal or roti' },
      { icon: 'fast-food-outline', title: 'Snacks', desc: 'Use in noodles or snacks' },
    ],
    detailsTable: [
      { label: 'Brand', value: 'Hewe Agro' },
      { label: 'Weight', value: '100g' },
      { label: 'Form', value: 'Powder' },
      { label: 'Organic', value: '100% Yes' },
      { label: 'Country', value: 'India' },
      { label: 'Shelf Life', value: '12 months' },
    ],
    reviews: [
      {
        name: 'Mrs. Sulekha Bhatt',
        loc: 'Vadodara, Gujarat',
        rating: 5,
        text: 'Very easy, tasty and ready to eat product. Authentic and assured quality Moringa powder!',
      },
      {
        name: 'Mrs. Nirmala Murali',
        loc: 'USA',
        rating: 4,
        text: 'Using for 3 months. Can be added to any food. Noticed glow in my face and feeling more active.',
      },
      {
        name: 'Mrs. Sandhya',
        loc: 'Japan',
        rating: 4,
        text: 'Anti-inflammatory properties helped me get over my pains and keeping me active all day!',
      },
    ],
  },

  {
    name: 'Moringa Munaga Multi Purpose Powder',
    price: 299,
    originalPrice: 349,
    image: 'https://heweagro.com/wp-content/uploads/2023/08/multipurpose.png?resize=500%2C500&ssl=1',
    tag: 'Multi-Use',
    bestseller: true,
    desc: 'Versatile Moringa powder for soups, curries, smoothies and more.',
    ingredients: [
      'Moringa leaf powder',
      'Natural spices',
      'Salt',
    ],
    benefits: [
      'All-purpose cooking',
      'High protein content',
      'Natural energy boost',
      'Gluten-free',
    ],
    nutrition: [
      { label: 'Energy', value: '205 kcal' },
      { label: 'Protein', value: '27.1g' },
      { label: 'Carbohydrates', value: '38.2g' },
      { label: 'Fat', value: '2.3g' },
      { label: 'Fibre', value: '19.2g' },
      { label: 'Calcium', value: '2003mg' },
      { label: 'Iron', value: '28.2mg' },
      { label: 'Vitamin C', value: '17.3mg' },
      { label: 'Vitamin A', value: '18.9mg' },
      { label: 'Potassium', value: '337mg' },
    ],
    howToUse: [
      { icon: 'restaurant-outline', title: 'With Rice', desc: 'Mix with hot rice + ghee' },
      { icon: 'nutrition-outline', title: 'Curries', desc: 'Add to dal, curries, soups' },
      { icon: 'cafe-outline', title: 'Drinks', desc: 'Blend in smoothies or juices' },
    ],
    detailsTable: [
      { label: 'Brand', value: 'Hewe Agro' },
      { label: 'Weight', value: '100g' },
      { label: 'Form', value: 'Powder' },
      { label: 'Organic', value: '100% Yes' },
      { label: 'Country', value: 'India' },
      { label: 'Shelf Life', value: '12 months' },
    ],
    reviews: [
      {
        name: 'Mrs. Sulekha Bhatt',
        loc: 'Vadodara, Gujarat',
        rating: 5,
        text: 'Very easy, tasty and ready to eat product. Authentic and assured quality Moringa powder!',
      },
      {
        name: 'Mrs. Nirmala Murali',
        loc: 'USA',
        rating: 4,
        text: 'Using for 3 months. Can be added to any food. Noticed glow in my face and feeling more active.',
      },
      {
        name: 'Mrs. Sandhya',
        loc: 'Japan',
        rating: 4,
        text: 'Anti-inflammatory properties helped me get over my pains and keeping me active all day!',
      },
    ],
  },

  {
    name: 'Hewe Moringa Munaga Tea Powder',
    price: 299,
    originalPrice: 379,
    image: 'https://heweagro.com/wp-content/uploads/2023/08/Moring-tea-img.webp?w=500&ssl=1',
    tag: 'Tea',
    bestseller: false,
    desc: 'A soothing Moringa tea blend with a mild, earthy flavour.',
    ingredients: [
      'Moringa leaf powder',
      'Tea blend',
    ],
    benefits: [
      'Calming & refreshing',
      'Rich in Vitamin C',
      'Supports metabolism',
      'No artificial flavors',
    ],
    nutrition: [
      { label: 'Energy', value: '180 kcal' },
      { label: 'Protein', value: '24.1g' },
      { label: 'Carbohydrates', value: '35.2g' },
      { label: 'Fat', value: '1.8g' },
      { label: 'Fibre', value: '16.2g' },
      { label: 'Calcium', value: '1800mg' },
      { label: 'Iron', value: '25.2mg' },
      { label: 'Vitamin C', value: '220mg' },
      { label: 'Vitamin A', value: '16.3mg' },
      { label: 'Potassium', value: '299mg' },
    ],
    howToUse: [
      { icon: 'cafe-outline', title: 'Tea', desc: 'Mix in hot water and serve warm' },
      { icon: 'water-outline', title: 'Morning Drink', desc: 'Drink morning or evening' },
      { icon: 'leaf-outline', title: 'With Honey', desc: 'Add honey if needed' },
    ],
    detailsTable: [
      { label: 'Brand', value: 'Hewe Agro' },
      { label: 'Weight', value: '100g' },
      { label: 'Form', value: 'Powder' },
      { label: 'Organic', value: '100% Yes' },
      { label: 'Country', value: 'India' },
      { label: 'Shelf Life', value: '12 months' },
    ],
    reviews: [
      {
        name: 'Mrs. Sulekha Bhatt',
        loc: 'Vadodara, Gujarat',
        rating: 5,
        text: 'Very easy, tasty and ready to eat product. Authentic and assured quality Moringa powder!',
      },
      {
        name: 'Mrs. Nirmala Murali',
        loc: 'USA',
        rating: 4,
        text: 'Using for 3 months. Can be added to any food. Noticed glow in my face and feeling more active.',
      },
      {
        name: 'Mrs. Sandhya',
        loc: 'Japan',
        rating: 4,
        text: 'Anti-inflammatory properties helped me get over my pains and keeping me active all day!',
      },
    ],
  },

  {
    name: 'Moringa Munaga Powder',
    price: 299,
    originalPrice: 349,
    image: 'https://heweagro.com/wp-content/uploads/2023/08/moringa-powder.png?resize=500%2C500&ssl=1',
    tag: 'Pure',
    bestseller: false,
    desc: 'Pure, organic Moringa powder — sprinkle on any food for a nutrition boost.',
    ingredients: [],
    benefits: [
      '92 nutrients',
      'High in calcium',
      'Pure & organic',
      'Versatile usage',
    ],
    nutrition: [
      { label: 'Energy', value: '205 kcal' },
      { label: 'Protein', value: '27.1g' },
      { label: 'Carbohydrates', value: '38.2g' },
      { label: 'Fat', value: '2.3g' },
      { label: 'Fibre', value: '19.2g' },
      { label: 'Calcium', value: '2003mg' },
      { label: 'Iron', value: '28.2mg' },
      { label: 'Vitamin C', value: '17.3mg' },
      { label: 'Vitamin A', value: '18.9mg' },
      { label: 'Potassium', value: '337mg' },
    ],
    howToUse: [
      { icon: 'nutrition-outline', title: 'Smoothies', desc: 'Blend in juices or smoothies' },
      { icon: 'restaurant-outline', title: 'Meals', desc: 'Mix into rice, dal or curries' },
      { icon: 'leaf-outline', title: 'Daily Use', desc: 'Use 1–2 teaspoons every day' },
    ],
    detailsTable: [
      { label: 'Brand', value: 'Hewe Agro' },
      { label: 'Weight', value: '100g' },
      { label: 'Form', value: 'Powder' },
      { label: 'Organic', value: '100% Yes' },
      { label: 'Country', value: 'India' },
      { label: 'Shelf Life', value: '12 months' },
    ],
    reviews: [],
  },
];